export const localizableStrings = {
  loginIdLabel: "Login Id",
  emailLabel: "Email",
  nameLabel: "Name",
  timeZoneLabel: "Time zone",
  homePageLabel: "Home page",
  aboutMeLabel: "About me",
  receiveNotificationLabel: "Receive notification of comments.",
  receiveNotificationMessage: "You will be sent an email when someone posts comments to your Blog or Album.",
  notificationMoreInfo: "You will be sent an email when someone posts comments to your Blog or Album.",
  passwordMainMessage: "Your password will be mailed to you.",
  emptyErrorMessage: "%s can't be empty.",
  aboutMeLengthErrorMessage: "Enter atleast 50 characters about yourself.",
  receiveCommentsNotificationErrorMessage: "Please check receive comment notifications.",
  invalidEmailError: "Enter a valid email.",
  invalidHomeUrlError: "Enter a valid home page URL.",
  unselectedTimeZoneError: "Please select a time zone",
  goText: "GO",
  chooseTimezoneText: "Choose time zones"
}